import 'dart:ui';

import 'package:get/get.dart';

class Language extends Translations{
  static const varsayilan = Locale('tr','TR');
  static final diller = [
    Locale('tr','TR'),
    Locale('en','US')
  ];
  @override
  Map<String, Map<String,String>> get keys => {
    'en_US':{
      'kullanıcı':'User',
      'restoran':'Restaurant',
      "burger" : "Burger",
      "kebap_türk_mutfağı": " Kebab & Turkish Cuisine",
      "tatlı": "Dessert",
      "pizza":"Pizza",
      "çiğ_köfte":"Çiğ Köfte",
      "kahve":"Coffee",
      "tantuni":"Tantuni",
      "waffle":"Waffle",
      "kokoreç":"Kokoreç",
      "tavuk":"Chicken",
      "kumpir":"Kumpir",
      "deniz_ürünleri":"Seafood",
      "tost_sandviç":"Toast & Sandwich",
      "ev_yemekleri": "Home Cooking",
      "kahvaltı_börek" : "Breakfast & Burrito",
      "makarna" : "Pasta",
      "mantı": "Mantı",
      "salata" : "Salad",
      "pastane_fırın":"Patisserie & Bakery",
      "pilav":"Rice",
      "çorba":"Soup",
      "İlginizi_Çekebilecek_Ürünler":"You May Be Interested In..",
      "dominos":"Dominos",
      "lahmacun":"Lahmacun",
      "döner":"Döner",
      "anasayfa":"Home Page",
      "kuponlarım":"My Coupons",
      "favoriler":"Favorites",
      "hesabım":"My Account",
      "Yakındaki_Restoranlar":"Nearby Restaurants",
      "Kurumsal":"Institutional",
      "biz_kimiz":"Who Are We",
      "tarihçemiz":"Our History",
      "hizmetler":"Services",
      "iletişim":"Communication",
      "bugün_ne_yesem":"What should I eat today...",
      "kuponunuz_yok":"You don't have a coupon",
      "konumunuz":"Current Location",
      "kaydet":"Save",
      "ad_soyad":"Name Surname",
      "e_posta":"Mail",
      "şifre":"Password",
      "yaş":"Age",
      "cinsiyet":"Gender",
      "erkek":"Male",
      "kadın":"Female",
      "cep_telefonu":"Phone Number",
      "adres":"Address",
      "telefon":"Phone",
      "website":"Website",
      "adres:":"Address:",
      "telefon:":"Phone:",
      "website:":"Website:",
      "yorumlar":"Comments",
      "çalışma_saatleri":"Working Hours",
      "Uzaklık":"Distance",
      "Puan":"Score",
      "Uzaklık:":"Distance:",
      "Puan:":"Score:",
      "sıralama":"Order",
      "kapat":"Close",
      "favori_restoranlar":"Favorite Restaurants",
      "favori_restoranınız_bulunmamaktadır":"You don't have a favorite restaurant.",
      "Alfabetik":"Alphabetical",
      "sıfırlama_bağlantısı_gönderildi":"Reset link sent.",
      "E-Mail_adresinize_şifre_sıfırlama_bağlantısı_gönderilecek": "A password reset link will be sent to your e-mail address.",
      "şifreler_eşleşmedi":"Passwords did not match.",
      "şifreni_sıfırla":"Reset your password",
      "geri":"Back",
      "sıfırla":"Reset",
      "şifremi_unuttum":"I forgot my password",
      "kayıt_ol":"Register",
      "giriş":"Login",
      "şifre_tekrar":"Password Again",
      "veya":"Or",
      "gönder":"Send",
      "kaydı_tamamlamak_için_formu_doldurunuz":"Fill out the form to complete registration",
      "geçersiz_telefon_numarası":"Invalid Phone Number",
      "onay_kod":"Confirmation code",
      "kategoriler":"Categories",
      "ad":"Name",
      "soyad":"Surname",
      "bu_kategoride_restoran_bulunamadı":"Could not find any resaurants in this category.",
      "çıkış_yap":"Log out",
      "değerlendirmeler":"Reviews",
      "değerlendirme_bulunmamaktadır":"No Reviews."
    },
    'tr_TR':{
      "kullanıcı": "Kullanıcı",
      "restoran" :"Restoran",
      "burger" : "Burger",
      "kebap_türk_mutfağı": "Kebap & Türk Mutfağı",
      "tatlı":"Tatlı",
      "pizza":"Pizza",
      "çiğ_köfte":"Çiğ Köfte",
      "kahve":"Kahve",
      "tantuni":"Tantuni",
      "waffle":"Waffle",
      "kokoreç":"Kokoreç",
      "tavuk":"Tavuk",
      "kumpir":"Kumpir",
      "deniz_ürünleri":"Deniz Ürünleri",
      "tost_sandviç":"Tost & Sandviç",
      "ev_yemekleri" : "Ev Yemekleri",
      "kahvaltı_börek" : "Kahvaltı & Börek",
      "makarna":"Makarna",
      "mantı":"Mantı",
      "salata":"Salata",
      "pastane_fırın":"Pastane & Fırın",
      "pilav":"Pilav",
      "çorba":"Çorba",
      "İlginizi_Çekebilecek_Ürünler":"İlginizi Çekebilecek Ürünler",
      "dominos":"Dominos",
      "lahmacun":"Lahmacun",
      "döner":"DÖner",
      "anasayfa":"Anasayfa",
      "kuponlarım":"Kuponlarım",
      "favoriler":"Favoriler",
      "hesabım":"Hesabım",
      "Yakındaki_Restoranlar":"Yakındaki Restoranlar",
      "Kurumsal":"Kurumsal",
      "biz_kimiz":"Biz Kimiz",
      "tarihçemiz": "Tarihçemiz",
      "hizmetler":"Hizmetler",
      "iletişim":"İletişim",
      "bugün_ne_yesem":"Bugün ne yesem...",
      "kuponunuz_yok":"Kuponunuz Yok",
      "konumunuz":"Konumunuz",
      "kaydet":"Kaydet",
      "ad_soyad":"Ad Soyad",
      "e_posta":"E-posta",
      "şifre":"Şifre",
      "yaş":"Yaş",
      "cinsiyet":"Cinsiyet",
      "erkek":"Erkek",
      "kadın":"Kadın",
      "cep_telefonu":"Cep Telefonu",
      "adres":"Adres",
      "telefon":"Telefon",
      "website":"Website",
      "adres:":"Adres:",
      "telefon:":"Telefon:",
      "website:":"Website:",
      "yorumlar":"Yorumlar",
      "çalışma_saatleri":"Çalışma Saatleri",
      "Uzaklık":"Uzaklık",
      "Puan":"Puan",
      "Uzaklık:":"Uzaklık:",
      "Puan:":"Puan:",
      "sıralama":"Sıralama",
      "kapat":"Kapat",
      "favori_restoranlar":"Favori Restoranlar",
      "favori_restoranınız_bulunmamaktadır":"Favori Restoranınız Bulunmamaktadır",
      "Alfabetik":"Alfabetik",
      "sıfırlama_bağlantısı_gönderildi":"Sıfırlama bağlantısı gönderildi.",
      "E-Mail_adresinize_şifre_sıfırlama_bağlantısı_gönderilecek":"E-Mail adresinize şifre sıfırlama bağlantısı gönderilecek.",
      "şifreler_eşleşmedi":"Şifreler eşleşmedi.",
      "şifreni_sıfırla":"Şifreni sıfırla.",
      "geri":"Geri",
      "sıfırla":"Sıfırla",
      "şifremi_unuttum": "Şifremi unuttum",
      "kayıt_ol":"Kayıt Ol",
      "giriş":"Giriş",
      "şifre_tekrar":"Şifre Tekrar",
      "veya":"Veya",
      "gönder":"Gönder",
      "kaydı_tamamlamak_için_formu_doldurunuz" :" Kaydı tamamlamak için formu doldurunuz",
      "geçersiz_telefon_numarası":"Geçersiz Telefon Numarası",
      "onay_kod":"Onay Kod",
      "kategoriler":"Kategoriler",
      "ad":"Ad",
      "soyad":"Soyad",
      "bu_kategoride_restoran_bulunamadı":"Bu kategoride restoran bulunamadı.",
      "çıkış_yap":"Çıkış Yap",
      "değerlendirmeler":"Değerlendirmeler",
      "değerlendirme_bulunmamaktadır":"Değerlendirme Bulunmamaktadır.",
    }
  };
}